# Generated by Django 3.1.7 on 2021-05-09 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(max_length=5, verbose_name='社員NO')),
                ('reported', models.DateField(verbose_name='報告日')),
                ('degrees', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='体温')),
                ('condition', models.BooleanField(blank=True, choices=[('', ''), (True, '異常なし'), (False, '異常あり')], default='', null=True, verbose_name='体調')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='備考')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='登録者')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日')),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name_plural': '体調管理DB',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(max_length=5, verbose_name='社員NO')),
                ('h_date', models.DateField(blank=True, null=True, verbose_name='日付')),
                ('flag', models.IntegerField(blank=True, choices=[('', ''), (1, '公休日'), (2, '有給休暇'), (3, '午前半休'), (4, '午後半休'), (5, '代替休日'), (6, '振替休日'), (7, '会社都合'), (8, '夏季休暇'), (9, '慶弔休暇'), (10, '病気休暇'), (11, 'リフレッシュ休暇'), (99, 'その他')], null=True, verbose_name='フラグ')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='内容')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='登録者')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日')),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name_plural': '社員休日マスタ',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(max_length=5, verbose_name='社員NO')),
                ('staff_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='社員名称')),
                ('assigned', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='登録者')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日')),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name_plural': '社員マスタ',
            },
        ),
    ]
