# Generated by Django 3.1.7 on 2021-05-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='health',
            table='Health',
        ),
        migrations.AlterModelTable(
            name='holiday',
            table='Holiday',
        ),
        migrations.AlterModelTable(
            name='member',
            table='Member',
        ),
    ]
